"""add exercise_templates table

Revision ID: 04f938201019
Revises: 2a1b3c4d5e6f
Create Date: 2026-05-25 17:38:22.434951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f938201019'
down_revision: Union[str, Sequence[str], None] = '2a1b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('revoked_refresh_tokens', 'revoked_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revoked_refresh_tokens', 'revoked_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_table('exercise_templates')
    # ### end Alembic commands ###
